language: objective-c
osx_image: xcode9.1
cache:
- bundler
- cocoapods
before_install:
- bundle install
- pod repo update
script:
- fastlane test;
# Versões de produção para Release na AppStore
- if [ $TRAVIS_BRANCH == "master" ]; then
  fastlane screenshots;
fi

# Versões de desenvolvimento subindo para TestFlight
- if [ $TRAVIS_BRANCH == "desenv" ]; then
  fastlane beta;
fi