language: objective-c
osx_image: xcode9.1
cache:
- bundler
- cocoapods
before_install:
- bundle install
- pod repo update
script:
- fastlane test;

# Versões de desenvolvimento subindo para TestFlight
  - if [ $POD_LINT == "YES" ]; then
      fastlane beta;
    fi