language: objective-c
osx_image: xcode9.1
cache:
- bundler
- cocoapods
before_install:
- bundle install
- pod repo update

script:
- fastlane test;
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then fastlane screenshots; fi
