language: objective-c
osx_image: xcode9.1
cache:
- bundler
- cocoapods
before_install:
- bundle install
- pod repo update
master:
  script: 
    - fastlane test;
    - fastlane screenshots;
development:
  script: 
    - fastlane test;