fastlane_version "2.68.0"

generated_fastfile_id "374a945e-9ada-4130-a843-eb8e4b220bd3"

default_platform :ios

desc "Runs all the tests"
lane :test do
    scan(scheme: "CaronaDev")
end

desc "Submit a new Beta Build to Apple TestFlight"
desc "This will also make sure the profile is up to date"
lane :beta do
    # increment_build_number
    build_number = increment_build_number

    # build your iOS app
    gym(scheme: "CaronaProd")

    # upload to Testflight
    pilot(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
end

desc "Deploy a new version to the App Store"
lane :release do
    # snapshot
    capture_screenshots(reinstall_app: true, app_identifier: "br.com.jjfernandes87.Carona", skip_open_summary: true)

    # upload screenshots to iTunes Connect
    upload_to_app_store

    # build your iOS app
    gym(scheme: "CaronaProd")

    deliver(force: true)
    # frameit
end
